project_id = 'tailoring-platform'

[api]
port = 54321
schemas = ['public', 'storage', 'auth']

[db]
port = 54322
major_version = 15

[studio]
port = 54323

[inbucket]
port = 54324

[auth]
site_url = 'http://localhost:3000'
additional_redirect_urls = ['http://localhost:3000']
jwt_expiry = 900
enable_phone_signup = true
enable_phone_autoconfirm = false

[auth.sms.twilio]
enabled = false
